FROM node:16

# Set env vars
ARG API_KEY
ENV API_KEY=${API_KEY}
ARG AUTH_DOMAIN
ENV AUTH_DOMAIN=${AUTH_DOMAIN}
ARG PROJECT_ID
ENV PROJECT_ID=${PROJECT_ID}
ARG STORAGE_BUCKET
ENV STORAGE_BUCKET=${STORAGE_BUCKET}
ARG MESSAGING_SENDER_ID
ENV MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
ARG APP_ID
ENV APP_ID=${APP_ID}
ARG MEASUREMENT_ID
ENV MEASUREMENT_ID=${MEASUREMENT_ID}

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN yarn install

# Bundle app source
COPY . .

# Our app listen on port 3001
EXPOSE 3001

RUN yarn compile

CMD [ "node", "dist/main.js" ]